language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
script:
  - yarn install
  - npm run build
deploy:
  provider: surge
  skip_cleanup: true
  domain: react-bookshelf.surge.sh
  project: ./build/
on:
  branch: master
